### ISSUE TITLE
aria2.conf not recognised

### ISSUE THREAD

**Issue by ghost** [clamsawd/aria2-static-builds#14]
`aria2.conf` does not get recognised. 
must use `--conf-path=`.

not sure if should be here or https://github.com/aria2/aria2/issues

**Comment by dmesg00** [comment]
I only build aria2. I don't know the bugs of the program. ¿What platform do you use? ¿Windows or Linux?

I also will test the program to check this error.

**Comment by ghost** [comment]
no need to (unless you want to of course..), 
I'll reopen it in https://github.com/aria2/aria2/issues

I use you build 0.34 Windows (x64)

**Comment by ghost** [comment]
both builds acts the same unless specify, they use whatever..
