### ISSUE TITLE
Difference between this and aria2 builds

### ISSUE THREAD

**Issue by tyeeman** [clamsawd/aria2-static-builds#18]
Hello
  I've been having trouble getting https working with the standard aria2 download. Spent hours trying to find the problem on Windows7. After all that wasted time, I tried your version here with ca-certificates and it worked first time. Thanks. I thought my problem was due to ciphers. Wireshark could not tell me what was wrong. TLS 1.2 was working then I saw the cipher list sent, then I got failure. Is this the reason you have your version here? Thanks again.

**Comment by dmesg00** [comment]
Not really. The version I compile uses libraries and a configuration that makes it work on older versions of Windows (like XP or 2000 Server). They are also static builds and everything is included in the binary (both on Windows and Linux). On Linux this is an advantage, as it allows it to work on all distributions.

**Comment by DriverTerminator** [comment]
> makes it work on older versions of Windows (like XP or 2000 Server).

Have can I build it to makes it work on older versions of Windows (like XP or 2000 Server)?
I buid it with msys2 on Windows. But need bcrypt.dll
