### ISSUE TITLE
[update request] v1.36.0

### ISSUE THREAD

**Issue by ghost** [clamsawd/aria2-static-builds#19]
Hello, thanks for having this repository, it works really well.
other than TLSv1.3, [the new version](https://github.com/aria2/aria2/releases/latest) solves some resume-corruption with extra flashing of file buffers.

<details><summary>also..</summary>
if possible please include in the exe resources the manifest to help this exe run without virtualization on Windows 10:

```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?> 
<assembly xmlns="urn:schemas-microsoft-com:asm.v1" manifestVersion="1.0"> 
  <trustInfo xmlns="urn:schemas-microsoft-com:asm.v3"> 
    <security> 
      <requestedPrivileges> 
        <requestedExecutionLevel level="asInvoker" uiAccess="false" /> 
      </requestedPrivileges> 
    </security> 
  </trustInfo> 
  <compatibility xmlns="urn:schemas-microsoft-com:compatibility.v1"> 
    <application> 
      <supportedOS Id="{8e0f7a12-bfb3-4fe8-b9a5-48fd50a15a9a}"></supportedOS> 
      <supportedOS Id="{1f676c76-80e1-4239-95bb-83d0f6d0da78}"></supportedOS> 
      <supportedOS Id="{4a2f28e3-53b9-4441-ba9c-d69d4a4a6e38}"></supportedOS> 
      <supportedOS Id="{35138b9a-5d96-4fbd-8e2d-a2440225f93a}"></supportedOS> 
      <supportedOS Id="{e2011457-1546-43c5-a5fe-008deee3d3f0}"></supportedOS> 
    </application> 
  </compatibility> 
</assembly> 
```
here is a compiled .res file 
[aria2c_manifest_to_embed.res.zip](https://github.com/q3aql/aria2-static-builds/files/7049287/aria2c_manifest_to_embed.res.zip)

</details>

<details><summary>edit:</summary>
it can support path longer than 260-characters using this updated manifest (if a user <a href="https://docs.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=cmd#enable-long-paths-in-windows-10-version-1607-and-later">has enabled it</a>) :  

```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?> 
<assembly xmlns="urn:schemas-microsoft-com:asm.v1" manifestVersion="1.0"> 
  <application xmlns="urn:schemas-microsoft-com:asm.v3"> 
    <windowsSettings> 
      <longPathAware xmlns="http://schemas.microsoft.com/SMI/2016/WindowsSettings">true</longPathAware> 
    </windowsSettings>
  </application> 
  <trustInfo xmlns="urn:schemas-microsoft-com:asm.v3"> 
    <security> 
      <requestedPrivileges> 
        <requestedExecutionLevel level="asInvoker" uiAccess="false" /> 
      </requestedPrivileges> 
    </security> 
  </trustInfo> 
  <compatibility xmlns="urn:schemas-microsoft-com:compatibility.v1"> 
    <application> 
      <supportedOS Id="{8e0f7a12-bfb3-4fe8-b9a5-48fd50a15a9a}"></supportedOS> 
      <supportedOS Id="{1f676c76-80e1-4239-95bb-83d0f6d0da78}"></supportedOS> 
      <supportedOS Id="{4a2f28e3-53b9-4441-ba9c-d69d4a4a6e38}"></supportedOS> 
      <supportedOS Id="{35138b9a-5d96-4fbd-8e2d-a2440225f93a}"></supportedOS> 
      <supportedOS Id="{e2011457-1546-43c5-a5fe-008deee3d3f0}"></supportedOS> 
    </application> 
  </compatibility> 
</assembly> 
 
```

Here is a VERSIONINFO block for the exe:  
```txt

1 VERSIONINFO
FILEVERSION 1,36,0,0
PRODUCTVERSION 1,36,0,0
FILEOS 0x40004
FILETYPE 0x1
{
BLOCK "StringFileInfo"
{
	BLOCK "040904B0"
	{
		VALUE "Comments", "https://github.com/q3aql/aria2-static-builds"
		VALUE "FileDescription", "Multipart Command-Line Downloader"
		VALUE "InternalName", "aria2c.exe"
		VALUE "OriginalFilename", "aria2c.exe"
		VALUE "CompanyName", "Aria2"
		VALUE "LegalCopyright", "https://github.com/q3aql/aria2-static-builds/blob/master/LICENSE.txt"
		VALUE "ProductName", "Aria2C"
		VALUE "FileVersion", "1.36.0.0"
		VALUE "ProductVersion", "1.36.0.0"
	}
}

BLOCK "VarFileInfo"
{
	VALUE "Translation", 0x0409 0x04B0  
}
}
```
and simple icon I've made
[MAINICON.ico.zip](https://github.com/q3aql/aria2-static-builds/files/7062845/MAINICON.ico.zip)  
so right click the exe file gives extra information in WIndows, which is more user-friendly:  
![2021-08-27_004927](https://user-images.githubusercontent.com/415238/131040743-ccd99c10-4a82-4f97-8927-297653784686.jpg)  
![2021-08-27_004648](https://user-images.githubusercontent.com/415238/131040764-894dfe81-3f11-430c-b8ae-5b254afbeda1.jpg)  
![2021-08-27_004808](https://user-images.githubusercontent.com/415238/131040771-4f62f3ca-dc65-4c19-af68-715ed96e3001.jpg)  

here is a compiled `.res` file. you can use [ResourceHacker ](http://www.angusj.com/resourcehacker/) post-compile to manually embed the resource file 
(use the menu to import, choose from exe/dll/res) without the need to change your compilation scripts (unless you want to).  
[icon_versioninfo_manifest_with_longpath_support.res.zip](https://github.com/q3aql/aria2-static-builds/files/7062896/icon_versioninfo_manifest_with_longpath_support.res.zip)

</details>

**Comment by dmesg00** [comment]
Ooohhh! I didn't know a new version had been released. I'll update the build scripts and try to post the new versions as soon as I can. Thanks for letting me know.

**Comment by dmesg00** [comment]
@eladkarako I only use Linux and from this system I cross-compile to Windows. The resources hacker tool does not work running with Wine. If you want I can give you the binaries, you apply the manifest and send them back to me so I can publish them.

[aria2-1.36.0-win-32bit-build1.zip](https://github.com/q3aql/aria2-static-builds/files/7068174/aria2-1.36.0-win-32bit-build1.zip)
[aria2-1.36.0-win-64bit-build1.zip](https://github.com/q3aql/aria2-static-builds/files/7068176/aria2-1.36.0-win-64bit-build1.zip)

**Comment by ghost** [comment]
<del>Sure, couple of minutes. (will be edited soon)</del> - ✔  

[aria2-1.36.0-win-64bit-build1.zip](https://github.com/q3aql/aria2-static-builds/files/7068908/aria2-1.36.0-win-64bit-build1.zip)  
[aria2-1.36.0-win-32bit-build1.zip](https://github.com/q3aql/aria2-static-builds/files/7068901/aria2-1.36.0-win-32bit-build1.zip)  
![2021-08-27_212342](https://user-images.githubusercontent.com/415238/131174316-355a6ab2-582e-45aa-ad28-ca9daf833fd1.jpg)  

<details>
<summary>and I'll just leave this here for reference...</summary>
exe for easy diff:<br/>
<a href="https://github.com/q3aql/aria2-static-builds/files/7068838/variations.zip">variations.zip</a><br/>
<img src="https://user-images.githubusercontent.com/415238/131172398-e84d81db-5651-41a9-b466-2e3f9446aa04.jpg" /><br/>
resources (raw and compiled, same for x32 and x64).<br/>
<a href="https://github.com/q3aql/aria2-static-builds/files/7068933/aria2c.rc.zip">aria2c.rc.zip</a><br/>
<a href="https://github.com/q3aql/aria2-static-builds/files/7068934/aria2c.res.zip">aria2c.res.zip</a><br/>

<br/>
btw. this is <a href="https://github.com/eladkarako/gcc-manifest-icon/blob/master/Makefile">how I embed .rc into the compilation's makefile</a> (minor modifications needed for linux). <br/>
don't use <strong>that</strong> manifest though.
</details>

<details><summary>updated build2 binaries</summary>
updated embedded (and side-by-side) manifest with support for Windows 10 new <code>SegmentHeap</code>.  


<details><summary>manifest</summary>

```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?> 
<assembly xmlns="urn:schemas-microsoft-com:asm.v1" manifestVersion="1.0"> 
  <dependency optional="yes"> 
    <dependentAssembly> 
      <assemblyIdentity name="Microsoft.Windows.Common-Controls" 
        version="6.0.0.0" publicKeyToken="6595b64144ccf1df" 
        type="win32" processorArchitecture="*" language="*" /> 
    </dependentAssembly> 
  </dependency> 
  <application xmlns="urn:schemas-microsoft-com:asm.v3"> 
     <windowsSettings> <dpiAware      xmlns="http://schemas.microsoft.com/SMI/2005/WindowsSettings">true/PM</dpiAware>                     </windowsSettings> 
     <windowsSettings> <dpiAwareness  xmlns="http://schemas.microsoft.com/SMI/2016/WindowsSettings">PerMonitorV2,PerMonitor</dpiAwareness> </windowsSettings> 
     <windowsSettings> <longPathAware xmlns="http://schemas.microsoft.com/SMI/2016/WindowsSettings">true</longPathAware>                   </windowsSettings> 
     <windowsSettings> <heapType      xmlns="http://schemas.microsoft.com/SMI/2020/WindowsSettings">SegmentHeap</heapType>                 </windowsSettings> 
  </application> 
  <trustInfo xmlns="urn:schemas-microsoft-com:asm.v3"> 
    <security> 
      <requestedPrivileges> 
        <requestedExecutionLevel level="asInvoker" uiAccess="false" /> 
      </requestedPrivileges> 
    </security> 
  </trustInfo> 
  <compatibility xmlns="urn:schemas-microsoft-com:compatibility.v1"> 
    <application> 
      <supportedOS Id="{8e0f7a12-bfb3-4fe8-b9a5-48fd50a15a9a}" /> 
      <supportedOS Id="{1f676c76-80e1-4239-95bb-83d0f6d0da78}" /> 
      <supportedOS Id="{4a2f28e3-53b9-4441-ba9c-d69d4a4a6e38}" /> 
      <supportedOS Id="{35138b9a-5d96-4fbd-8e2d-a2440225f93a}" /> 
      <supportedOS Id="{e2011457-1546-43c5-a5fe-008deee3d3f0}" /> 
    </application> 
  </compatibility> 
</assembly> 
 
```

</details>

this one has the missing icon too.  

<a href="https://github.com/q3aql/aria2-static-builds/files/8247947/aria2-1.36.0-win-32bit-build2.zip" download="aria2-1.36.0-win-32bit-build2.zip">aria2-1.36.0-win-32bit-build2.zip</a>  
<a href="https://github.com/q3aql/aria2-static-builds/files/8247960/aria2-1.36.0-win-64bit-build2.zip" download="aria2-1.36.0-win-64bit-build2.zip">aria2-1.36.0-win-64bit-build2.zip</a>  

</details>

**Comment by dmesg00** [comment]
I'll check the executables and if they are compatible on XP and 10, I'll swap mine for yours. Thanks for everything.
