### ISSUE TITLE
build of aria2 1.25 for Raspberry

### ISSUE THREAD

**Issue by cxjava** [clamsawd/aria2-static-builds#2]
Can you provide compiled version for raspberry?

**Comment by cxjava** [comment]
[aria2c.1.25.raspberry.zip](https://github.com/q3aql/aria2-static-builds/files/399318/aria2c.1.25.raspberry.zip)
I have build it by myself. Thanks!

**Comment by dmesg00** [comment]
@cxjava Sorry for not answering. 
What are the libraries that has been compiled in this build?. You can see it with the command `aria2c -v`.

**Comment by cxjava** [comment]
@q3aql It is ok for me.

The enabled features are here:

```
** Configuration **
Enabled Features: Async DNS, BitTorrent, Firefox3 Cookie, GZip, HTTPS, Message Digest, Metalink, XML-RPC
Hash Algorithms: sha-1, sha-224, sha-256, sha-384, sha-512, md5, adler32
Libraries: zlib/1.2.8 expat/2.2.0 sqlite3/3.10.1 OpenSSL/1.0.2h c-ares/1.10.0
Compiler: gcc 4.8.3 20140303 (prerelease)
  built by   x86_64-pc-linux-gnu
  targetting arm-unknown-linux-gnueabihf
  on         Aug  3 2016 05:04:27
System: Linux 4.1.19-v7+ #858 SMP Tue Mar 15 15:56:00 GMT 2016 armv7l

Report bugs to https://github.com/aria2/aria2/issues
Visit https://aria2.github.io/
```

I build it from Dockerfile.
[Dockerfile.raspberrypi.ok.txt](https://github.com/q3aql/aria2-static-builds/files/400679/Dockerfile.raspberrypi.ok.txt)

**Comment by dmesg00** [comment]
@cxjava Maybe I will compile in the future a version for ARM (Raspberry) but with SFTP (libssh2) support included. Thanks for your dockerfile.

**Comment by dmesg00** [comment]
@cxjava I added a Raspberry Pi build ([aria2-1.25.0-linux-gnu-arm-rbpi-build1.tar.bz2](https://github.com/q3aql/aria2-static-builds/releases/download/v1.25.0/aria2-1.25.0-linux-gnu-arm-rbpi-build1.tar.bz2)) with support for all available protocols and with updated libraries. Can you try it and tell me if run correctly?

**Comment by cxjava** [comment]
@q3aql  I download it and run **aria2c -v .** and out put like below:

```
** Configuration **
Enabled Features: Async DNS, BitTorrent, Firefox3 Cookie, GZip, HTTPS, Message Digest, Metalink, XML-RPC, SFTP
Hash Algorithms: sha-1, sha-224, sha-256, sha-384, sha-512, md5, adler32
Libraries: zlib/1.2.8 expat/2.2.0 sqlite3/3.13.0 OpenSSL/1.0.2h c-ares/1.11.0 libssh2/1.7.0
Compiler: gcc 4.8.3 20140303 (prerelease)
  built by   x86_64-pc-linux-gnu
  targetting arm-unknown-linux-gnueabihf
  on         Aug  7 2016 17:29:10
System: Linux 4.1.19-v7+ #858 SMP Tue Mar 15 15:56:00 GMT 2016 armv7l

Report bugs to https://github.com/aria2/aria2/issues
Visit https://aria2.github.io/
```

and also run it correctly, works fine! Thanks for your hard work! I will use your version.

**Comment by dmesg00** [comment]
@cxjava Perfect! Thanks! I also will compile the next releases of aria2.
