### ISSUE TITLE
Where can I get Aria2 on ARMv5 

### ISSUE THREAD

**Issue by AdminHcat** [clamsawd/aria2-static-builds#21]
i tried run /mnt/md0/sofaware/aria2-1.36.0-linux-gnu-arm-rbpi-build1$ ./aria2c

 but it returned "Illegal instruction"

**Comment by rampageX** [comment]
```
aria2 version 1.36.0
Copyright (C) 2006, 2019 Tatsuhiro Tsujikawa

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

** Configuration **
Enabled Features: Async DNS, BitTorrent, Firefox3 Cookie, GZip, HTTPS, Message Digest, Metalink, XML-RPC, SFTP
Hash Algorithms: sha-1, md5, adler32
Libraries: zlib/1.2.11 libxml2/2.9.12 sqlite3/3.36.0 OpenSSL/1.1.1l c-ares/1.18.1 libssh2/1.10.0
Compiler: gcc 10.3.0
  built by  armv7l-unknown-linux-uclibceabi
  on        Dec 12 2021 11:40:42
System: Linux 2.6.36.4brcmarm #2 SMP PREEMPT Mon Nov 15 22:39:40 CST 2021 armv7l
```
[aria2c.tar.gz](https://github.com/q3aql/aria2-static-builds/files/7698166/aria2c.tar.gz)

**Comment by AdminHcat** [comment]
> 

still return "Illegal instruction",   I need ARMv5 te ,thankyou

**Comment by rampageX** [comment]
> > 
> 
> still return "Illegal instruction", I need ARMv5 te ,thankyou

file aria2c:

`aria2c: ELF 32-bit LSB executable, ARM, EABI5 version 1 (GNU/Linux), statically linked`

This one test on bcm4708(armv7l without vfp = arm5te).

What exactly hardware platform are you? What cpu?

**Comment by AdminHcat** [comment]
> > > 
> > 
> > 
> > still return "Illegal instruction", I need ARMv5 te ,thankyou
> 
> file aria2c:
> 
> `aria2c: ELF 32-bit LSB executable, ARM, EABI5 version 1 (GNU/Linux), statically linked`
> 
> This one test on bcm4708(armv7l without vfp = arm5te).
> 
> What exactly hardware platform are you? What cpu?

![image](https://user-images.githubusercontent.com/50044729/145703738-3968ee42-54ed-44e2-977a-fb85edc1a44f.png)

**Comment by rampageX** [comment]
Try this one:
[aria2c_musl.tar.gz](https://github.com/q3aql/aria2-static-builds/files/7698269/aria2c_musl.tar.gz)

**Comment by AdminHcat** [comment]
> Try this one: [aria2c_musl.tar.gz](https://github.com/q3aql/aria2-static-builds/files/7698269/aria2c_musl.tar.gz)

Can run, thank you very much!
