### ISSUE TITLE
Cann't build with msys2 on Windows?

### ISSUE THREAD

**Issue by DriverTerminator** [clamsawd/aria2-static-builds#24]
Somebody can tell me, how to build with msys2 on Windows?

**Comment by DriverTerminator** [comment]
I have Fix it.
I build win32 aria2c.exe with msys2 on Windows 10.
But it still need "bcrypt.dll", I donn't why.

**Comment by dmesg00** [comment]
Did you compile it using OpenSSL or Windows TLS?

**Comment by dmesg00** [comment]
@RedHairSakuragiHanamichi  My builds don't work for you either?

* [aria2-1.36.0-win-32bit-build1.7z](https://github.com/q3aql/aria2-static-builds/releases/download/v1.36.0/aria2-1.36.0-win-32bit-build1.7z)
* [aria2-1.36.0-win-32bit-build2.7z](https://github.com/q3aql/aria2-static-builds/releases/download/v1.36.0/aria2-1.36.0-win-32bit-build2.7z)

**Comment by DriverTerminator** [comment]
https://github.com/q3aql/aria2-static-builds/releases/download/v1.36.0/aria2-1.36.0-win-32bit-build2.7z


build2 can work on XP
but i want dll，so I want build it by myself



---Original---
From: ***@***.***&gt;
Date: Mon, Feb 21, 2022 03:22 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [q3aql/aria2-static-builds] Cann't build with msys2 on Windows?(Issue #24)




 
@RedHairSakuragiHanamichi  My builds don't work for you either?
  
aria2-1.36.0-win-32bit-build1.7z 

aria2-1.36.0-win-32bit-build2.7z 
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by DriverTerminator** [comment]
OpenSSL


---Original---
From: ***@***.***&gt;
Date: Mon, Feb 21, 2022 03:20 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [q3aql/aria2-static-builds] Cann't build with msys2 on Windows?(Issue #24)




 
Did you compile it using OpenSSL or Windows TLS?
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by dmesg00** [comment]
The library "bcrypt.dll" does not exist on Windows XP. This library is a dependency on modern Windows systems when using the system's own SSL/TLS library.

If you want to build a Windows XP compatible version, you must compile aria2 using OpenSSL instead of the Windows SSL/TLS library.

You must make sure that you have built OpenSSL correctly and that aria2 then detects it in the "configure" process.

**Comment by dmesg00** [comment]
Also, in case of problems, try overriding SFTP support, as it sometimes uses Windows TLS instead of OpenSSL, which would cause the problem.

**Comment by DriverTerminator** [comment]
I sure that I have built OpenSSL correctly and that aria2 then detects it in the "configure" process.

But I donn't know how to&nbsp;compile aria2 using OpenSSL instead of the Windows SSL/TLS library?

---Original---
From: ***@***.***&gt;
Date: Mon, Feb 21, 2022 03:33 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [q3aql/aria2-static-builds] Cann't build with msys2 on Windows?(Issue #24)




 
The library "bcrypt.dll" does not exist on Windows XP. This library is a dependency on modern Windows systems when using the system's own SSL/TLS library.
 
If you want to build a Windows XP compatible version, you must compile aria2 using OpenSSL instead of the Windows SSL/TLS library.
 
You must make sure that you have built OpenSSL correctly and that aria2 then detects it in the "configure" process.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by dmesg00** [comment]
**When you run ./configure --prefix.....blablablabla before doing the "make" command, it shows you which libraries it has detected and will use.**

**Once the program has been compiled, running the command "aria2c.exe -v" will show you which libraries it has been compiled with.**

q3aql@devuan ~> **aria2c -v**
aria2 version 1.36.0
Copyright (C) 2006, 2019 Tatsuhiro Tsujikawa

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

** Configuration **
Enabled Features: Async DNS, BitTorrent, Firefox3 Cookie, GZip, HTTPS, Message Digest, Metalink, XML-RPC, SFTP
Hash Algorithms: sha-1, sha-224, sha-256, sha-384, sha-512, md5, adler32
Libraries: zlib/1.2.11 expat/2.4.1 sqlite3/3.36.0 **OpenSSL/1.1.1l** c-ares/1.17.2 libssh2/1.9.0
Compiler: gcc 10.2.1 20210110
  built by  x86_64-pc-linux-gnu
  on        Aug 27 2021 13:08:17
System: Linux 5.16.10-xanmod1 #0~git20220216.ea7a824 SMP Wed Feb 16 16:10:14 UTC 2022 x86_64

Report bugs to https://github.com/aria2/aria2/issues
Visit https://aria2.github.io/
q3aql@devuan ~>

**Comment by DriverTerminator** [comment]
Yes, I use "--with-openssl".
and "aria2c -v" print "OpenSSL/1.1.1l" either the same as you.
but it still need need bcypt.dll

---Original---
From: ***@***.***&gt;
Date: Mon, Feb 21, 2022 03:47 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [q3aql/aria2-static-builds] Cann't build with msys2 on Windows? (Issue #24)




 
When you run ./configure --prefix.....blablablabla before doing the "make" command, it shows you which libraries it has detected and will use.
 
Once the program has been compiled, running the command "aria2c.exe -v" will show you which libraries it has been compiled with.
 
***@***.*** ~&gt; aria2c -v
 aria2 version 1.36.0
 Copyright (C) 2006, 2019 Tatsuhiro Tsujikawa
 
This program is free software; you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation; either version 2 of the License, or
 (at your option) any later version.
 
This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.
 
** Configuration **
 Enabled Features: Async DNS, BitTorrent, Firefox3 Cookie, GZip, HTTPS, Message Digest, Metalink, XML-RPC, SFTP
 Hash Algorithms: sha-1, sha-224, sha-256, sha-384, sha-512, md5, adler32
 Libraries: zlib/1.2.11 expat/2.4.1 sqlite3/3.36.0 OpenSSL/1.1.1l c-ares/1.17.2 libssh2/1.9.0
 Compiler: gcc 10.2.1 20210110
 built by  x86_64-pc-linux-gnu
 on        Aug 27 2021 13:08:17
 System: Linux 5.16.10-xanmod1 #0~git20220216.ea7a824 SMP Wed Feb 16 16:10:14 UTC 2022 x86_64
 
Report bugs to https://github.com/aria2/aria2/issues
 Visit https://aria2.github.io/
 ***@***.*** ~&gt;
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by dmesg00** [comment]
Then it is because the libssh2 library is using the Windows SSL/TLS. Try changing the "--with-libssh2" parameter to "--without-libssh2" when compiling. Then we can see if the problem is there.

**Comment by DriverTerminator** [comment]
thank you.
I will try it tomorrow.



---Original---
From: ***@***.***&gt;
Date: Mon, Feb 21, 2022 04:08 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [q3aql/aria2-static-builds] Cann't build with msys2 on Windows? (Issue #24)




 
Then it is because the libssh2 library is using the Windows SSL/TLS. Try changing the "--with-libssh2" parameter to "--without-libssh2" when compiling. Then we can see if the problem is there.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by DriverTerminator** [comment]
> Then it is because the libssh2 library is using the Windows SSL/TLS. Try changing the "--with-libssh2" parameter to "--without-libssh2" when compiling. Then we can see if the problem is there.

When I build aria2 with "--without-libssh2",then aria2c.exe show "GetTickCont64" on Windows XP.

**Comment by DriverTerminator** [comment]
the problem is msys2 on windows.
now I try Ubuntu x64.
But I don't known how to intall 32-bit compilation environment.
Can you help me please

**Comment by dmesg00** [comment]
You can see the comment on build scripts. Install the packages in the comment lines.

**Comment by DriverTerminator** [comment]
Thanks again. I compiled with Ubuntu and solved all the problems
