### ISSUE TITLE
Add LICENCE file + Link in README

### ISSUE THREAD

**Issue by vmullet** [clamsawd/aria2-static-builds#4]
Hello,
I checked your project and it is very interesting. I saw that the licence was precised on your website(https://aria2.github.io/) but not in the repository (no LICENCE file) so I was thinking to add it. Also , I think it would be good to add a link to your LICENCE in your README.

**Comment by dmesg00** [comment]
@LostArchives aria2 is not my project, is the project of [@tatsuhiro-t](https://github.com/tatsuhiro-t). I only compile a static builds of aria2 for Windows & Linux and my packages also include the license. This repository only have unofficial builds & scripts.
