### ISSUE TITLE
How to static link gcc when build dynamic version of libaria2?

### ISSUE THREAD

**Issue by jashking** [clamsawd/aria2-static-builds#6]
When build the dynamic version of libaria2, it depends on libgcc_s_sjlj-1.dll and libstdc++-6.dll.
And the file size of libstdc++-6.dll is nearly 10.9 MB, so is there a way to static link to gcc?

**Comment by dmesg00** [comment]
@jashking I don't know the way to link statically, but you can reduce the size of libstdc++-6.dll using the command:

$ strip --strip-all libstdc++-6.dll
