### ISSUE TITLE
aria2-1.34.0-linux-gnu-arm-rbpi-build1.tar.bz2 doesn't run on Raspiberry 1

### ISSUE THREAD

**Issue by rocdeng** [clamsawd/aria2-static-builds#9]
aria2-1.34.0-linux-gnu-arm-rbpi-build1.tar.bz2 doesn't run on Raspiberry 1. Said 'Illegal instruction'.

**Comment by dmesg00** [comment]
@rocdeng Sorry, the builds are for Raspberry Pi 2 and newer.
